Developer
makires/WeatherProjectTestOrion pull request #2
Opened 2021-12-27 09:10 UTC by makires

Test pull request through GitHub. 
MainCopy is empty start project, developer is current work branch.

2021-12-28 10:03 UTC, ismail9001 requested changes

2021-12-28 10:03 UTC, ismail9001 commented on Podfile
> +  pod 'Alamofire', '~> 5.5'
добавить поды в гит игнор

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Assets.xcassets/cloudyBackground.imageset/Contents.json
> +      "filename" : "zrj-TPjcRLA.png",
используй понятные названия в названиях картинок (все проверить)

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/HourlyCurrentWeather.swift
> +let hourlyCurrentWeather = [
это ведь уже не нужно?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/ListDailyWeather.swift
> +let listDaily = [
это нужно?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/ListDailyWeather.swift
> +    let temp1: String
непонятные названия тампературы

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/ListDailyWeather.swift
> +    let nameDay: String
просто day

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var windDirection = ""
используй enum у тебя ограниченное количество направлений

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var temperatureCurrent = ""
число

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var pressureHPa  = ""
число

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var windKph  = ""
число

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var text = ""
что за текст?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var humidity  = ""
число

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var feelsLikeTemperature  = ""
число

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var icon = ""
енум

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    init() { }
зачем пустой инит?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +struct HourlyCurrentWeather {
в отдельный файл

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +        icon = "https:" + response.current.condition.iconURL
оно нам нужно?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    init() { }
убери везде где не нужны

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +        arrayHoursAll = response.forecast.forecastday[0].hour
а если нет нулевого элемента?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +            } else if Date(timeIntervalSince1970: TimeInterval(hour.timeEpoch)) >= currentDate {
если выше ничего не делаем оставь просто этот if

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/MainView.swift
> +//            .border(.green, width: 2)
убирай весь закомментированный код

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/MainView.swift
> +            VStack(spacing: 0) {
.zero

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/MainView.swift
> +                weatherVM.getAllWeather(for: weatherVM.cityTitleStatic, locale: locale)
locale можем вынести во viewModel?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/MainView.swift
> +struct ContentView_Previews: PreviewProvider {
превью удаляй все они нужны только на этапе верстки

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +let feelsLike: LocalizedStringKey = ", Feels like "
выноси все в единый локализационный файл

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +                .font(.system(size: 80, weight: .thin))
стили сделай через модификаторы

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +                    VStack {
зачем эти VSTack?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +            AsyncImage(url: URL(string: weather.icon)) { image in
мы вроде отказались от загрузки изображений погоды?

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +            .frame(width: 60, height: 60)
подумай как сделать паддингами

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +                    .opacity(0)
не совсем понятна конструкция с пустым цветом и нулевой прозрачностью

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +struct DailyWeatherRow: View {
в отдельную сабвью

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +                    .foregroundColor(Color(#colorLiteral(red: 0.24, green: 0.24, blue: 0.26, alpha: 0.6)))
используй цвета через ColorSet в ассетах

2021-12-28 10:03 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +            let gridItems = [GridItem(spacing: 10), GridItem( spacing: 4), GridItem(alignment: .trailing)]
выноси из боди

2021-12-28 10:03 UTC, ismail9001 commented on en.lproj/Localizable.strings
> +"Nizhny Novgorod" = "Nizhny Novgorod";
пиши ключи с уникальными Uppercased

пример "FEELS_LIKE"

2021-12-28 11:59 UTC, makires commented on Podfile
> +  pod 'Alamofire', '~> 5.5'
Done. Pods ignored. 
commit 966a197

2021-12-28 15:05 UTC, makires commented on WeatherProjectTestOrion/Assets.xcassets/cloudyBackground.imageset/Contents.json
> +      "filename" : "zrj-TPjcRLA.png",
Done. Commit 136b829. Other images has correct names.

2021-12-28 15:15 UTC, makires commented on WeatherProjectTestOrion/Main/Model/HourlyCurrentWeather.swift
> +let hourlyCurrentWeather = [
No, file deleted. It was dummy model.
Commit 76b8ae5.

2021-12-28 15:15 UTC, makires commented on WeatherProjectTestOrion/Main/Model/ListDailyWeather.swift
> +let listDaily = [
Commit 76b8ae5 also.

2021-12-28 15:18 UTC, makires commented on WeatherProjectTestOrion/Main/Model/ListDailyWeather.swift
> +    let temp1: String
Commit 76b8ae5.
I'll remember about naming.

2021-12-28 16:20 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +            let gridItems = [GridItem(spacing: 10), GridItem( spacing: 4), GridItem(alignment: .trailing)]
Done, property gridItems moved out from body.
Commit 7d93b28.

2021-12-28 16:20 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +                    .opacity(0)
Этот элемент необходим для отслеживания координат верхнего левого угла во время скрола. Без него не к чему прикрепить бэкграунд, из которого передается значение координаты, (через структуру PreferenceKey), на основе этого события я скрываю часовой прогноз. Подумать над другим вариантом реализации?
На счет opacity(0), для PR удалю, прозрачность осталась для дальнейшего эксперимента с реализацией исчезающего часового прогноза, так как еще нет итогового варианта.
Commit 7d93b28.

2021-12-28 16:39 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +struct DailyWeatherRow: View {
Done. Separate DailyWeatherRow.
Commit 7282760.

2021-12-28 16:42 UTC, makires commented on WeatherProjectTestOrion/Main/Model/ListDailyWeather.swift
> +    let nameDay: String
File deleted. 
Commit 76b8ae5 also.

2021-12-28 18:01 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var temperatureCurrent = ""
Эта модель используется в текстовых элементах во вью, если поставить число, то придется делать опционал (либо инициализировать какую-нибудь дефолтную модель для response API).  В любом случае, если будет nil, надо что-то показать, а показывать число 0 в температуре, когда температуры совсем нет, не лучший вариант, или я ошибаюсь в понимании комментария? И еще эта модель инициализируется с этими свойствами, и она @Published во вью модель. Я попробовала поменять, там получается полный хаос во вью и со string interpolation 😬 
Text("\(weather.current.temperatureCurrent ?? 0 )")
Оставить как есть или покопаться и заменить?

2021-12-28 18:20 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var text = ""
replace textWeatherCondition. Done.
Commit a19309a713bd25b5ed175bf0e8a9b6415461e5d8

2021-12-28 21:59 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +        arrayHoursAll = response.forecast.forecastday[0].hour
Done. Used optional binding to find out whether on optional contains value. Add property .first? and deleted index [0].

2021-12-28 22:07 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    init() { }
Done. Also add custom init through extension.
Commit 9c074b5dc6b04cd95532e4f3cbc01cde90321842 and a81586e7af460a4aebd47802f3cb09a23dddd08b

2021-12-28 22:11 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +struct HourlyCurrentWeather {
Done. 841a43f80828d2c527d42ecf4e4b1826dfabf6e2

2021-12-28 22:18 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +        icon = "https:" + response.current.condition.iconURL
Рассуждаю по этой же логике.
https://github.com/makires/WeatherProjectTestOrion/pull/2#discussion_r775791770
Модель Weather создается с дефолт значениями в виде пустых срок, эта модель @Published. Как только срабатывает запрос на сервер и приходит ответ, то значения от сервера конвертируются в стринги для модели, соответсвенно для указанных свойств значения устанавливаются через инициализатор и сразу конвертируются. 
Еще момент: temperatureConverter это computed property, в нем сразу добавляется необходимые символы градуса º и + для температуры.

iconURL - не смогла пока продумать как отображает "чистое" небо, если ответ приходит в ночное время.
это тоже к этому комментарию https://github.com/makires/WeatherProjectTestOrion/pull/2#discussion_r775795037

2021-12-28 22:21 UTC, makires commented on WeatherProjectTestOrion/Main/View/MainView.swift
> +struct ContentView_Previews: PreviewProvider {
Done. All PreviewProvider deleted.
7282760e1c6373b193170b3e518b6790f82f66b4

2021-12-28 22:28 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +            AsyncImage(url: URL(string: weather.icon)) { image in
Не смогла пока продумать как отображать "чистое" небо, если ответ приходит в ночное время, то по картинке там луна, если день - то солнце. Описание погоды в этом случае имеет одинаковый цифровой код, а как встроить в модель проверку на ночь-день не успела продумать . 
Заметку оставила.

2021-12-28 22:45 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var windDirection = ""
enum для направления ветра добавила, использую его при парсинге в апи. 
По части строкового значения для ветра в этой модели, необходимы разъяснения. Тут как с температурой, дефолтное значение будет пустой строкой, если ответ от сервера не придет. 🙄
82afa136bc427741590699808e9ae84951d6aa4b

2021-12-28 22:53 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var feelsLikeTemperature  = ""
also https://github.com/makires/WeatherProjectTestOrion/pull/2#discussion_r776018866

2021-12-28 22:54 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var humidity  = ""
also https://github.com/makires/WeatherProjectTestOrion/pull/2#discussion_r776018866

2021-12-28 22:54 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var windKph  = ""
also https://github.com/makires/WeatherProjectTestOrion/pull/2#discussion_r776018866

2021-12-28 22:54 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var pressureHPa  = ""
also https://github.com/makires/WeatherProjectTestOrion/pull/2#discussion_r776018866

2021-12-28 23:01 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var icon = ""
не понимаю до конца как сделать иконку через enum.
иконка погоды основывается на Int который приходит от сервера. Я делаю switch, так как использовать число в case внутри enum нельзя. Сведения об иконке погоды анализируются через extension ConditionWeather и уже на основе визуального сходства я выбирала символы из sf symbols.  Нужен совет

2021-12-28 23:02 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +            } else if Date(timeIntervalSince1970: TimeInterval(hour.timeEpoch)) >= currentDate {
Done.

2021-12-28 23:03 UTC, makires commented on WeatherProjectTestOrion/Main/View/MainView.swift
> +//            .border(.green, width: 2)
Done.

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +var maxTemperature = "15º"
зачем они здесь?

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +    @Published var weatherCurrent = Weather()
переменные обычно инициализируются до основного инициализатора

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +//    @State var cityName: String = ""
убираем все комментарии

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                    VStack(spacing: 2) {
сделай через Magic number

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                            .padding(EdgeInsets(top: 6, leading: 0, bottom: 6, trailing: 8))
попробуй реализовать иначе, много магических чисел

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +            print("появилась ячейка \(cityName)")
убираем

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                    )
должно быть на 63 строке

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +        .padding(.vertical, 4)
магические числа

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                    .frame(width: 10.5, height: 15)
попробуй через высоту в 16 и aspectRatio

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                Text("Субъект рф")
localized

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +            .foregroundColor(Color("subText"))
сделай цвета через расширение Color

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +    var iconAndCurrentTemperature: some View {
непонятно название нужно переделать

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +            Image(systemName: "cloud")
картинки тоже через енум расширения сделай

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                Text("10") + Text(Localization.kmH.localized)
можно сделать одной конкатинацией _ плюс много статичных данных

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                Text(minTemperature) + Text("/") + Text(maxTemperature)
Text(minTemperature + "/" + maxTemperature)

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/ListLocationsView.swift
> +        ScrollView {
соблюдай выравнивание

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/CitiesList/View/ListLocationsView.swift
> +
пустые строки swiftlint должен был об этом сказать

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherRow.swift
> +                        .tracking(0.35)
это можно вынести в стиль текста

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/TestPluginView/TestSwiftUIPluginForFigma/CurrentWeatherViewTP.swift
> +            ZStack {
зачем он нужен?

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/Main/View/TestPluginView/TestSwiftUIPluginForFigma/DetailsForCurrentWeatherViewTP.swift
> +            .offset(x: -194, y: 28)
если ты используешь столько offset явно чтото не так с версткой

2022-01-08 11:39 UTC, ismail9001 commented on WeatherProjectTestOrion/Network/APICurrentWeatherModel.swift
> +extension Int {
почему расширения находятся в файле с моделями

2022-01-10 11:01 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +                    VStack {
unnecessary, deleted.

2022-01-12 17:13 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +                    .foregroundColor(Color(#colorLiteral(red: 0.24, green: 0.24, blue: 0.26, alpha: 0.6)))
Done.

2022-01-12 17:13 UTC, makires commented on en.lproj/Localizable.strings
> +"Nizhny Novgorod" = "Nizhny Novgorod";
Done.

2022-01-12 17:13 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +var maxTemperature = "15º"
Deleted. It was temporary.

2022-01-12 19:06 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +        icon = "https:" + response.current.condition.iconURL
Done. icon for clear day for all variants with icon "sun.max"

2022-01-12 19:07 UTC, makires commented on WeatherProjectTestOrion/Main/View/MainView.swift
> +                weatherVM.getAllWeather(for: weatherVM.cityTitleStatic, locale: locale)
На данный момент при размещении locale во ViewModel идентификатор локализации не считывается.

2022-01-12 19:07 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +let feelsLike: LocalizedStringKey = ", Feels like "
Done.

2022-01-12 19:11 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +                .font(.system(size: 80, weight: .thin))
Done.

2022-01-12 19:12 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/DailyWeatherListView.swift
> +                    .opacity(0)
Переделала на другой вариант.

2022-01-12 19:13 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +    @Published var weatherCurrent = Weather()
Deleted.

2022-01-12 19:13 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +//    @State var cityName: String = ""
Done.

2022-01-12 19:14 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +            print("появилась ячейка \(cityName)")
Done.

2022-01-12 19:16 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                Text("Субъект рф")
Весь Location приходит от сервера на английском. 
Q: Что делать , если API не поддерживает русский по всем субъектам РФ и другим странам?

2022-01-12 19:16 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +            .foregroundColor(Color("subText"))
Colors - done.

2022-01-12 19:17 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +            Image(systemName: "cloud")
Done.

2022-01-12 19:17 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                Text(minTemperature) + Text("/") + Text(maxTemperature)
Конкатенация строк, done.

2022-01-12 19:17 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/ListLocationsView.swift
> +
Починила SwiftLint.

2022-01-12 19:18 UTC, makires commented on WeatherProjectTestOrion/Main/View/TestPluginView/TestSwiftUIPluginForFigma/CurrentWeatherViewTP.swift
> +            ZStack {
Deleted.

2022-01-12 19:21 UTC, makires commented on WeatherProjectTestOrion/Network/APICurrentWeatherModel.swift
> +extension Int {
Перенесла в общий файл с Modifiers+Extension.
Q: файл перегружен. Как организовывать?

2022-01-12 19:22 UTC, makires commented on WeatherProjectTestOrion/Main/View/TestPluginView/TestSwiftUIPluginForFigma/DetailsForCurrentWeatherViewTP.swift
> +            .offset(x: -194, y: 28)
Линий тестовый файл, удален.

2022-01-12 19:23 UTC, makires commented on WeatherProjectTestOrion/Main/Model/Weather.swift
> +    var windDirection = ""
Done.

2022-01-12 19:24 UTC, makires commented on WeatherProjectTestOrion/Main/View/MainView.swift
> +            VStack(spacing: 0) {
Перенесен в файл с константами.

2022-01-12 19:31 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                    .frame(width: 10.5, height: 15)
Done. Worked.

2022-01-13 21:01 UTC, makires commented on WeatherProjectTestOrion/Network/APICurrentWeatherModel.swift
> +extension Int {
Done.

2022-01-13 21:01 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/ListLocationsView.swift
> +        ScrollView {
Done.

2022-01-13 21:02 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +                Text("10") + Text(Localization.kmH.localized)
Done.

2022-01-13 21:02 UTC, makires commented on WeatherProjectTestOrion/CitiesList/View/CityRowView.swift
> +    var iconAndCurrentTemperature: some View {
Renamed.

2022-01-13 21:03 UTC, makires commented on WeatherProjectTestOrion/Main/View/SubView/CurrentWeatherView.swift
> +            .frame(width: 60, height: 60)
Deleted.

2022-01-13 21:07 UTC, merged